name: depoly-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ajobs gitbook macos x64
    steps:
      - uses: actions/checkout@v4
      - run: touch ajobsLearn.txt
