name: depoly-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ajobs gitbook macos x64
    steps:
      - name: Check Ref Type
        run: |
          if [[ ${{ github.ref_type }} != 'tag' ]]; then
            echo " ${GITHUB_REF#refs/heads/} : ${{ github.event.repository.name }} is not tag"
            exit 1
          fi 
      - uses: actions/checkout@v4
      - run: touch ajobsLearn-02.txt
